version: '3.8'

services:
  wordpress:
    image: ${DC_IMAGE_NAME}:${DC_IMAGE_TAG}
    environment:
      - WORDPRESS_DB_HOST=${DC_WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${DC_WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${DC_WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${DC_WORDPRESS_DB_PASSWORD}
    restart: always
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    restart: always
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge